name = input('Enter a sentence :')
print('원래 문장:',name)
name = name.replace('_',' ')
print('수정한 문장:',name)
print('a는 {}번 나왔다.'.format(name.count('a')))
print('e는 {}번 나왔다.'.format(name.count('e')))
print('u는 {}번 나왔다.'.format(name.count('u')))
print('space는 {}번 나왔다.'.format(name.count(' ')))
name = name.upper()
print('모두 대문자로 바꾸면:',name)
